language: csharp
dist: trusty
mono: none
dotnet: 2.1.502
solution: ci-test.sln

install:
  - dotnet restore
  - dotnet tool install coveralls.net --version 1.0.0 --tool-path .
  - ls
  
script:
  - dotnet build -c Debug
  - dotnet test ci-test.Test/ci-test.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - csmacnz.Coveralls --opencover -i ci-test.Test/coverage.opencover.xml --useRelativePaths
  
before_deploy:
  - git config --local user.name "Denchi"
  - git config --local user.email "denchisoft@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  
deploy:
  provider: releases
  api_key: ${github_api_key}
  file: "ci-test-2/bin/Debug/netcoreapp2.1/ci-test-2.dll"
  skip_cleanup: true